name: Sync on DOM Cloud

'on':
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3



      with:
        webhook_url: https://my.domcloud.co/api/githubdeploy
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
        data: |
          {"commands":[
            "git pull",
            "cp .env.production .env", 
            "mkdir -p data", 
            "chmod 755 data", 
            "docker-compose up --build -d"
          ],"wait":1}

    - name: Check deployment status
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: https://my.domcloud.co/api/githubdeploycheck
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_auth: ${{ secrets.WEBHOOK_AUTH }}